### PR TITLE
Discord Plugin fixes

### PR DESCRIPTION
**Pull request by marshyonline**
Util is required here
Sill trying to work out why its bouncing back from the Discord API
```[pmon]  2018-12-06 23:12:08  info : Discord: Message Sent
[pmon]  2018-12-06 23:12:35  error : Invalid Form Body
embeds[0].author.url: Not a well formed URL.
```
Getting the above error with the hostname filled or not filled

### CODE REVIEW

**Comment by DanrwAU** [comment]
Strange... I thought I fixed that already! 

That error look familiar but I can't remember what the cause was, I'll take a look tomorrow if you haven't figured it out :)

**Comment by marshyonline** [comment]
looks like its ignoring the hostname from process.json and returning my servers hostname (thats not a valid url) and discord doesn't like that

**Comment by marshyonline** [comment]
Ok - PM2 was just being a bitch and I need to tell it when the process.json fill was again for it to reload the evn's from it. 

The above change is all that should be required now

**Comment by davidmckenzie** [comment]
Merging, thanks dude!

**Pull request merged**
