### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by davidmckenzie**
FYI @marshyonline / @DanrwAU force merging this one - few dependency updates to resolve security vulns

### CODE REVIEW

**Comment by marshyonline** [comment]
Acknowledged
Looks go to me anyway 👌

**Comment by DanrwAU** [comment]
Whats the procedure for updating these, should an NPM INSTALL update them?

**Comment by marshyonline** [comment]
Npm install will do the job 
Npm update should work too :)

**Comment by marshyonline** [comment]
Can we flag this as a new release?

**Comment by davidmckenzie** [comment]
Yeah `npm i` does the trick :)

I'll be pushing the FTS stuff later today and will bump up version with that

**Pull request merged**
