### PR TITLE
Add exec shell command on selected alias

### PR DESCRIPTION
**Pull request by all3kcis**
Like Pushover or email alert, that's add the possibility to exec shell command for selected aliases.

I developt it because i'm a firefighter and I use Pagermon with this feature to turn on the light on night hours if my pager ring.

here is an example to use :
On my personnal alias :
capture

And in lights.py ( for example )
```python
from datetime import time, datetime

#### VARS
now = datetime.now()
# Night hours
start_time = time(22, 00)
stop_time = time(9, 00)
# Light duration
duration = 60 * 8	


### CODE

if ( now.time() >= start_time or now.time() <= stop_time or True):
	# Exec script
	## your script here
else:
	print 'Time not match'
```

### CODE REVIEW

**Comment by marshyonline** [comment]
One the merge conflicts are resolved there is a +1 from me

**Comment by all3kcis** [comment]
Oh yes...
Maybe I can just use enabled / disabled option on aliases and exec file stored in folder pagermon/local-scripts ?
For example : Alias id 52 with "ShellCmd" option enabled, when a message address match, we looking for "pagermon/local-scripts/alias-52.sh" and exec it if exist.

Or #130 is an another solution yes

**Comment by davidmckenzie** [comment]
I'm gonna put some work into #130 today, will see how far I get there and let ya know :)

**Comment by all3kcis** [comment]
Please close and see #154

**Pull request closed without merging**
