### PR TITLE
Add Telegram Support, Add Automated Database upgrade - Bump to version 0.1.9

### PR DESCRIPTION
**Pull request by DanrwAU**
Adds Telegram support as a notification provider.

Requires the following on existing databases

```
ALTER TABLE capcodes ADD COLUMN telegram INTEGER DEFAULT 0; 
ALTER TABLE capcodes ADD COLUMN telechat TEXT;
```

### CODE REVIEW

**Comment by s3m1s0n1c** [comment]
Looks good.. All works 👍

**Comment by DanrwAU** [comment]
Fairly confident this works as expected, I tested a whole bunch last night with no issues. 
I also tweaked thee message format a little, if anyone can come up with anything better, feel free. 
Here's how it currently looks
image

**Comment by davidmckenzie** [comment]
Awesome! Before we merge I'd like to have a think about #114 - perfect opportunity to solve that problem at the same time.

I also wanna have a quick look at the library's docos to see if we'll run into any issues with initiating `new telegram` on each message. If it's just setting up methods then should be fine, but if it's actually doing a pass of credentials at that point and retrieving another auth token or something, then could run into API limits later on.

**Comment by DanrwAU** [comment]
`I also wanna have a quick look at the library's docos to see if we'll run into any issues with initiating new telegram on each message. If it's just setting up methods then should be fine, but if it's actually doing a pass of credentials at that point and retrieving another auth token or something, then could run into API limits later on.`

Good catch, the library i used doesn't seem to be the most active one, it was just the one the last fork had used, the other one seems to be more regularly developed but would have the same issue. 
https://github.com/yagop/node-telegram-bot-api

**Comment by davidmckenzie** [comment]
Had a quick read of the current lib, it doesn't do anything fancy on its initial call, unless you have updates enabled, and they're off by default, so should be safe as is :)

It'd probably be more efficient and safer to set up the `t` variable up the top just after calling the library - unless there'd ever be a case where we'd want different API keys for different aliases. One key can be used for many channels, yeah?

**Comment by DanrwAU** [comment]
Yep,

My understanding is the token is per bot, i can't see any use case for multiple bots so it should be safe to declare it once, the only consideration would be if it makes a call to validate - it may slow down message processing for messages without notifications

If we're going to go down that route the same probably applies to pushover, i can't ever seeing there being a need for multiple application keys (except to skirt their message limits which i wouldn't be writing in anyway) so it could be done at the top as well.

**Comment by davidmckenzie** [comment]
You guys wanna review again? I've pulled the DB stuff out and added some logic to upgrade the DB schema when required.

It's controlled by the 'release' int in app.js, so all we need to do to push an update to schema is update that number and add the relevant bits into db.js. It will attempt to add missing columns as required. If more complex schema changes are required, we can probably add some logic in there to drop and recreate the tables.

Also moved the `t` definition up to the top - I haven't tested this bit yet, only tested the DB upgrade bits

**Comment by marshyonline** [comment]
These changes look super good, Ill pull down tonight and submit a review 👍

**Comment by s3m1s0n1c** [comment]
> Yep,
> 
> My understanding is the token is per bot, i can't see any use case for multiple bots so it should be safe to declare it once, the only consideration would be if it makes a call to validate - it may slow down message processing for messages without notifications
> 

Yeah the token is per bot..  I believe you can send messages to different channels/users from the same bot but only in the same instance.. you cant have 2 bots with the same name.

> If we're going to go down that route the same probably applies to pushover, i can't ever seeing there being a need for multiple application keys (except to skirt their message limits which i wouldn't be writing in anyway) so it could be done at the top as well.

Nah you shouldn't need multiple API keys as I don't we will hit the following criterias
- mess More then 30 messages per seconds
- mess More then 20 messages per minute 

They recommend not sending more then 1 message a second which may happen if the system spits out lots of pagers at the same time but they have the above limits

Maybe we can add tho to throw a error in log/console when 429 error is detected so we know the limit is being hit.

**Comment by DanrwAU** [comment]
Tested Telegram with these changes, looks all good. 

DB Upgrade worked well on my production database as well (140k messages). 

Added a commit for a field i forgot to change the name of in the settings page :smile: 👍

**Comment by s3m1s0n1c** [comment]
Yep Tested Telegram as well.. Works good..
DB Updated...

Can't review but good to go :)

**Comment by DanrwAU** [comment]
> Date: (dateofmessage) Time: (Timeofmessage)
> Message: (Message)
> Brigade: (Alias) **Agency: (Agency)**

The agency should be shown in the title of the current template, not a fan of having the date and time, telegram has that anyway.

**Comment by davidmckenzie** [comment]
Merging as is, we can make changes to message format later if needed :)

**Comment by s3m1s0n1c** [comment]
Okays so Documentation for Telegram API has been done.

https://github.com/s3m1s0n1c/pagermon/wiki/Telegram

I plan on doing some more documentation on the rest of Pagermon when I get time.

Is this OK or do u want more detail/pics?

Thanks

**Comment by marshyonline** [comment]
Love some good pics in guides

Could also make use of code blocks for things like examples :) 
Top work as always sonic

**Comment by s3m1s0n1c** [comment]
Okays no worries.. Will add it in..

**Comment by davidmckenzie** [comment]
Nice, thanks dude :) Have added you to collaborators if you wanted to edit direct on the repo's wiki

**Comment by s3m1s0n1c** [comment]
> Nice, thanks dude :) Have added you to collaborators if you wanted to edit direct on the repo's wiki

No worries, Thanks

**Pull request merged**
