### PR TITLE
Catch errors in Reader.js to prevent halting due to badly formatted pager messages

### LINKED ISSUE #346: TypeError: Cannot read property '1' of null
Crashed today with this message.  Running on Raspberry Pi.

```
readline.js:1032
            throw err;
            ^

TypeError: Cannot read property '1' of null
    at Interface.rl.on (/home/pi/pagermon/client/reader.js:104:48)
    at Interface.emit (events.js:189:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._line (readline.js:638:8)
    at Interface._ttyWrite (readline.js:926:16)
    at Socket.onkeypress (readline.js:168:10)
    at Socket.emit (events.js:189:13)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
    at Socket.onData (readline.js:1022:36)
Signal caught, exiting!

User cancel, exiting...
```

### PR DESCRIPTION
**Pull request by CramShack**
# Description

As described in error #346  catches any errors during the parsing of pager messages, thus preventing any sudden exiting of the script.  I expect the issue is recurring due to unexpected characters in messages. I've had this personally happen in pager messages where there are line breaks.

Fixes # (issue)

Try/catch wrapped around the main line.match parsing section. Logs to console.error.

** Parsing itself should be expanded upon to accommodate unusually formatted pages. **

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Ran the reader with the same messages fed through to replicate the cause of "TypeError: Cannot read property '1' of null" killing the script.

### CODE REVIEW

**Comment by CramShack** [comment]
> > > 
> > 
> > 
> > I'd say pop them in another pull request, as its your contribution....
> > Also, in re to multi-line, better to use a JS solution rather than relying on the system to do new line replacements. Could maybe separate each line into multiple messages, but that may require more work than its worth.
> 
> The problem is that thats typically not how Linux piping works. The script executes every line individually. You could delay sending the message to see if theres another line, but then multiple messages sent together would end up as a single message. You would be better to remove the line break and execute reader.js once for one message, than treating every line as though there might be another coming. Especially when the line break will get stripped out by the time it makes it to the client anyway by the browser, because browsers dont render newlines in html anyway.

As I said, more work to refactor it for an uncommon use-case. 


Here, I was referring to using JS for stripping the newlines rather than using a linux command, 
> Also, in re to multi-line, better to use a JS solution rather than relying on the system to do new line replacements.

**Comment by geelongmicrosoldering** [comment]
Js doesnt see the newlines is my point. Js never sees "message body \n more message body". Js just gets "process this", followed by "now process this".

Im not sure what the issue with not using JS is, given that the reader.js file is specifically made to read the output of a linux command (multimon-ng) anyway, which is being fed from another (rtl-fm). If you eliminate the non js commands, you also eliminate the need for the js.

**Comment by SloCompTech** [comment]
> if (address.length > 2 && trimMessage.length > 1)

Here probably should be:

> if (address.length > 1 && trimMessage.length > 1)

since 9 is already valid pocsag address if I remember correctly

**Comment by geelongmicrosoldering** [comment]
> > if (address.length > 2 && trimMessage.length > 1)
> 
> Here probably should be:
> 
> > if (address.length > 1 && trimMessage.length > 1)
> 
> since 9 is already valid pocsag address if I remember correctly

If 9 is valid then >1 wont catch it either.

I should have explained the 2 though. The erroneous messages from memory contained a single space or an arbitrary character, and were coming from an address of 99.

I actually wasnt aware that that was a valid address. Nonetheless, if you change it to >1 it will still filter the empty messages that were causing the issue. It wont filter the arbitrary characters, but thats what filters are for, so that works for me.

**Comment by eopo** [comment]
I did already completely rewrite reader.sh in #434, but no-one that originally had the problem did participate in testing, and since it's an edge case ...

**Comment by marshyonline** [comment]
Can we confirm this is still needed?
Drop back into non-wip if so plz :)

**Comment by DanrwAU** [comment]
closed due to inactivity

**Pull request closed without merging**
