### PR TITLE
make whitespace less white

### PR DESCRIPTION
**Pull request by davidmckenzie**
Haven't tested this yet but shouldn't cause any problems, will pull down to my live install later today. Just cleaning up the whitespace a *lot* - converted to spaces over tabs and made the api.js all 2-space indentation for readability

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Hmm I'm getting an auth failure in logs when updating capcodes but it still processes... I have a vague recollection that was a thing long ago too. Otherwise no issues found.

**Comment by DanrwAU** [comment]
Yeah i get that every time, i recall reading something about it in an issue.. I'll pull down to my test box shortly and give it a run through.

**Comment by davidmckenzie** [comment]
Aha, that's right, I remember now. I think I filed it under "screw it, that'll do" 🤣

**Comment by marshyonline** [comment]
I think I'm the one who raised the original issue too 😂

**Comment by davidmckenzie** [comment]
\o/

Merging!

**Pull request merged**
