### PR TITLE
Email/SMTP intergration

### PR DESCRIPTION
**Pull request by marshyonline**
# Built in email support!

I have built in email support much like PDW.
New users need to make no DB changes, anyone updating from <=0.1.4 will need to run the following:

`ALTER TABLE capcodes ADD COLUMN mailenable INTEGER DEFAULT 0;`
`ALTER TABLE capcodes ADD COLUMN mailto TEXT;`
`ALTER TABLE capcodes ADD COLUMN pushpri TEXT;`

Supports SSL/TLS
Global on/off option in settings.
Per alias on/of
The TO address is set per alias and allow multiple recipients(Comma separated).

This update bumps the version to 0.1.5

Leverages the same query much like my pushover modification.

### CODE REVIEW

**Comment by marshyonline** [comment]
Before we merge this, I'm working on #66 
Two birds with one stone, seeing how the DB update could be going out anyway.

**Comment by marshyonline** [comment]
Latest commit apply's the suggested change in #66.
Have changed original pull req to include the db modification for it too

**Comment by kiwiscout** [comment]
Scratching my head wondering why the web service wouldn't restart. Then realised you can run node app.js.. oh look. Needed to add PM2 package 'nodemailer' to get it to start :D

**Comment by davidmckenzie** [comment]
Whoops :D

Updated the release notes to mention this. Thanks @kiwiscout!

**Pull request merged**
