### PR TITLE
Ignore not matching capcodes

### PR DESCRIPTION
**Pull request by all3kcis**
Use to ignore all messages where address not matching with the patern (javascript regex)

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Thanks for the PR! Not sure about this one though - what's it trying to solve that isn't solved by existing aliases with the filter checkbox selected?

You can already create aliases that are ignored with wildcard matching, so it seems like it would only really fit a very specific use-case where complex regex is required for the filtering, unless I'm missing something?

In the example given in the help text, you could just as easily create an alias with the address '00%' to filter out those messages

**Comment by all3kcis** [comment]
Yes, I need to ignore all message that match with /^(0|1)86, it is not possible with actual alias system

**Comment by DanrwAU** [comment]
I had to do something similar for an instance I setup for someone.

I ended up doing it on the pocsag receiver (in reader.js).

**Comment by davidmckenzie** [comment]
Going to close off this PR as I've implemented as a plugin in #130 / #135 - hit me up if this isn't what you had in mind and we can tweak the plugin :)

**Pull request closed without merging**
