### PR TITLE
Event fixes

### PR DESCRIPTION
**Pull request by marshyonline**
Increases the max events :D

### CODE REVIEW

**Comment by davidmckenzie** [comment]
Weird that the setMaxListeners would kill it like that... wonder if it has to be called further down or something. Could be we need to call it separately for each socket:

e.g.
```
io.sockets.on('connection', function (socket) {
    socket.setMaxListeners(20);
```

Does it show up in browser dev tools as trying to connect to the admin socket?

**Comment by marshyonline** [comment]
Im able to see the socket opening up on the client side.
You can see it by checking the frames of the web socket request.

This site is in HideCapcode mode and they seem to be coming over the admin socket ok

image

image

**Comment by DanrwAU** [comment]
Interesting.... It was 2am thanks for checking on your end.

I'll have a look later today and see if I can figure it out :smile:

**Comment by marshyonline** [comment]
Very strange, this was prior to the pushover fixes pulled into master today.
Ill run the update tonight and ensure something in there is broken :)

**Comment by DanrwAU** [comment]
It very well may be :confused:

**Comment by DanrwAU** [comment]
Interesting... 

I can see them being emitted to the socket - but the page is not refreshing....

image

image

**Comment by DanrwAU** [comment]
I quit.. 

Repulling it down from the merged one fixed it .... ignore me i guess 😠

**Comment by davidmckenzie** [comment]
My money's on caching - the client side JS was probably cached, so it didn't know what to do with the events

**Pull request merged**
