### PR TITLE
Add Discord Webhook Support and Twitter API Support

### PR DESCRIPTION
**Pull request by DanrwAU**
Add's support for posting messages directly to a Discord chat channel via Discord Webhook. 
image

Add's the ability to post pager messages to Twitter.
Requires a twitter developer account.

Allows for custom hashtags at the server and alias level.
image

### CODE REVIEW

**Comment by marshyonline** [comment]
You beat me to this one, ive been waiting for the weekend to build this in..
Can I suggest this? - https://www.npmjs.com/package/webhook-discord

You can simply pass it the full url via the settings page + it gives you a little more control over message posting and how messages are displayed via the message builder

**Comment by DanrwAU** [comment]
Haha leave boredom had me looking for something to do.

This one does look better for our purposes, I'll take a look at switching it out in the morning!

**Comment by marshyonline** [comment]
Ideally i would like to be able to display like this(Excuse my legal downloads 😄 )
Via an embed to make it really stand out with the colour being configurable
image

**Comment by davidmckenzie** [comment]
Discord.js is 👌 

You can do pretty embeds easily in discord.js, lemme grab some code from another project

**Comment by davidmckenzie** [comment]
```js
 var embed = new Discord.RichEmbed({
     timestamp: new Date(),
 });
embed.setColor(0xDDDDDD);
embed.setTitle(`**${row.message}**`);
embed.addField('Alias', `${row.alias}`);
embed.setAuthor('PagerMon', '', `http://someurl/`);
```

^ as an example. It's pretty :)

**Comment by DanrwAU** [comment]
Managed to get this going. 

I'm using the colors from the Alias at the moment, however it seems like the friendly names aren't always translated to the correct color. 
A good solution would be to have the colors always saved as the HEX vaule in the DB rather than names. 
This will allow them to be used anywhere going forward

image

**Comment by davidmckenzie** [comment]
Could use https://www.npmjs.com/package/colornames

**Comment by DanrwAU** [comment]
That looks like it would do the trick, i tried adding it to admin.main.js to do the conversion there as part of the save button without any luck.
Where would you have it doing it?

**Comment by davidmckenzie** [comment]
Only really need it in the discord bit, can't see a real driving need for it to be changing the db values :)

**Comment by DanrwAU** [comment]
.... This is why i'm not a programmer 😛 

Done!

**Comment by DanrwAU** [comment]
I might look into changing the settings page back to a URL String and splitting it up server side to make it more user friendly. 
A job for after afternoon nap time 😆

**Comment by DanrwAU** [comment]
Added Twitter Module as well as my developer account has been approved and it works great.
Solves https://github.com/davidmckenzie/pagermon/issues/127

**Comment by 112bzo** [comment]
Wow I follow your twitter test account. How did you implement that

I use PM 0.1.9Beta and like to have this working. Can you help me?

**Comment by marshyonline** [comment]
Other than those changes - Everything is super awesome and working well
Top work @DanrwAU

**Comment by marshyonline** [comment]
image

Opinions on this?
I think i prefer it without the "Message" apart

**Comment by DanrwAU** [comment]
Thanks, I hadn't managed to get up and get my laptop yet.

Your way looks nicer I'd say we go for that.

**Comment by marshyonline** [comment]
Gimme 5 - Ill push it out
5 days off work so i figured i might start doing somthing 😆

**Comment by DanrwAU** [comment]
> Gimme 5 - Ill push it out
> 5 days off work so i figured i might start doing somthing 😆
Thanks for that! 

I'm 3 weeks in to paternal leave so far 😜 i got so bored i started looking at replacing the database stuff with Knex..  That's a deep rabbit hole 😉

**Comment by davidmckenzie** [comment]
We can keep it 0.1.9 :) I haven't pushed 0.1.9 as a release yet so we can even bundle a couple more things in first if desired.

This branch is looking 👌 btw, do you want it merged now?

**Comment by DanrwAU** [comment]
Yep I'm done :-)

**Comment by davidmckenzie** [comment]
Beauty, merging!

**Pull request merged**
