### PR TITLE
API Sec Mode - fix new messages not showing capcode

### PR DESCRIPTION
**Pull request by marshyonline**
This Fixes capcodes not showing when logged in in api sec mode

### CODE REVIEW

**Comment by DanrwAU** [comment]
Good Work, I've been meaning to look into this!  

I'll  pull it down shortly and test it out 👍

**Comment by DanrwAU** [comment]
This one's not working for me, index is no longer being updated with new messages, the messages are showing in the websocket from developers tools 😕

**Comment by davidmckenzie** [comment]
This whole chunk of stuff is confusing :D 

@DanrwAU does it work when you have apisecurity disabled, but hidecapcode true? Should be the same code I think

**Comment by DanrwAU** [comment]
Definetly works with HideCapcode on - doesnt work in secure mode. 

The messages asre definetly showing in the socket tho 😦

**Comment by marshyonline** [comment]
Ok, that should be easy then

**Comment by marshyonline** [comment]
Ive broken git 😆 
Leave this one with me

**Pull request closed without merging**
