### PR TITLE
Fix Broken API Sec

### PR DESCRIPTION
**Pull request by marshyonline**
Attempt 2 after bringing the branch inline with master
@DanrwAU can you pull down a compleate fresh copy and try agian

I'm running this in prod - with API sec and Hide Capcodes enabled and can see new message's displayed correctly from the index.

### CODE REVIEW

**Comment by DanrwAU** [comment]
Sorry mate, still not working for me, i pulled down a fresh install and copied over my DB and Config files. 

Still getting the message showing in the websocket and not going to the front page. 

image

**Comment by DanrwAU** [comment]
My bad, this looks like an issue with SecureMode seperate from what your fixing.

Securemode isn't posting the AdminIO Socket in api.js. 

Your fix works for APISecurity and HideCapcode.

**Comment by DanrwAU** [comment]
Ok i've pushed a commit that fixed ApiSecurity by itself without duplicating any code 👍 .

Try it out and let me know how you go.

**Comment by marshyonline** [comment]
Ah this explains it then
I was running API Sec and Hide Capcode and must not have tested with api sec alone 
Happy to merge 👍

**Pull request merged**
