### PR TITLE
Message Search in Secure Mode

### LINKED ISSUE #116: Secure Mode - Searching Fails
Another one from me, i should stop reading logs.

Looks like searching is broken when secure mode is enabled. 
Searches return no results and the following is thrown at the console.
```
0|pagermon |     at /srv/pagermon/server/node_modules/express/lib/router/index.js:281:22
0|pagermon |     at param (/srv/pagermon/server/node_modules/express/lib/router/index.js:354:14)
0|pagermon |     at param (/srv/pagermon/server/node_modules/express/lib/router/index.js:365:14)
0|pagermon |     at Function.process_params (/srv/pagermon/server/node_modules/express/lib/router/index.js:410:3)
0|pagermon |     at next (/srv/pagermon/server/node_modules/express/lib/router/index.js:275:10)
0|pagermon |     at /srv/pagermon/server/routes/api.js:25:3
0|pagermon |     at Layer.handle [as handle_request] (/srv/pagermon/server/node_modules/express/lib/router/layer.js:95:5)
0|pagermon |     at trim_prefix (/srv/pagermon/server/node_modules/express/lib/router/index.js:317:13)
0|pagermon |     at /srv/pagermon/server/node_modules/express/lib/router/index.js:284:7
0|pagermon |     at Function.process_params (/srv/pagermon/server/node_modules/express/lib/router/index.js:335:12)
0|pagermon |     at next (/srv/pagermon/server/node_modules/express/lib/router/index.js:275:10)
0|pagermon |     at urlencodedParser (/srv/pagermon/server/node_modules/body-parser/lib/types/urlencoded.js:91:7)
0|pagermon |   name: 'AuthenticationError',
0|pagermon |   message: 'Unauthorized',
0|pagermon |   status: 401 }
```
This one is above my paygrade unfortunately 😞

### PR DESCRIPTION
**Pull request by marshyonline**
Resolves #116

Little bit dirty, but it gets the job done

### CODE REVIEW

**Comment by marshyonline** [comment]
Interesting, i didnt see this in dev.
I shall look over it and see whats going on.

The auth login is confusing as shit right now 😆

**Comment by davidmckenzie** [comment]
So this is weird, I'm having a play with this on a separate branch - looking at the actual error, it's throwing a 401 but returning the data... wtf.

**Comment by davidmckenzie** [comment]
Submitted a different thing in #118 that should solve this

**Comment by marshyonline** [comment]
Closing due to @davidmckenzie being a boss and doing this a better way 💯

**Pull request closed without merging**
